# Generated by Django 3.1.4 on 2021-01-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_group',
        ),
    ]
